### ISSUE TITLE
Migration to 10

### ISSUE THREAD

**Issue by hbrunn** [OCA/oca-custom#12]
Hi @legalsylvain, will you also work on this module? I've made a preliminary migration on https://github.com/hbrunn/oca-custom/tree/10.0 - this works, but I don't understand the dichotomy between the github_login and the x-github_login field.

Will you changes in the interface branch also need changes here?

As I don't have permissions on this repo, could you one someone else create an empty 10 branch so that I can create a PR?

**Comment by legalsylvain** [comment]
> Hi @legalsylvain, will you also work on this module? I've made a preliminary migration on https://github.com/hbrunn/oca-custom/tree/10.0 - this works, but I don't understand the dichotomy between the github_login and the x-github_login field.

This is for historicity reason.
1. OCA admin created a field by UI (x-github_login), on the beginning of the instance. (with view and so.)

2. Then, I wrote github connector module, that have a generic field. github_login. 

3. i wrote a custom module oca_custom. And to avoid to break OCA instance, I added a related field. The other advantage is that it's possible to fill the field (that is not readonly). Otherwise, with only the github connector, the field is readonly. (we assume that we create partner from github). In the OCA instance, partner are existing some times before github sync. (If partners are members for exemple and have paid membership).

I don't know if we have to remove this field. ( and I did'nt planned to port this module). Please ask to @gurneyalex. (if he's not on hollidays ;-))

> As I don't have permissions on this repo, could you one someone else create an empty 10 branch so that I can create a PR?

Done, https://github.com/OCA/oca-custom/tree/10.0

regards.

**Comment by hbrunn** [comment]
thank you so much! I'll drop the field then and write a migration script if necessary
